export const WS_PROFILE_CONNECTION_START = 'WS_PROFILE_CONNECTION_START';
export const WS_PROFILE_CONNECTION_SUCCESS = 'WS_PROFILE_CONNECTION_SUCCESS'; 
export const WS_PROFILE_CONNECTION_CLOSED = 'WS_PROFILE_CONNECTION_CLOSED';
export const WS_PROFILE_GET_FEED_MESSAGE = 'WS_PROFILE_GET_FEED_MESSAGE';
export const WS_PROFILE_CONNECTION_ERROR = 'WS_PROFILE_CONNECTION_ERROR';

export const wsStart = () => ({
  type: WS_PROFILE_CONNECTION_START
})
